"""v0.34 #7 — Orbiter pText extraction is byte-identical to the reference SDK.

The recupero decoder ports orbiter-sdk core.ts ``getPTextFromTAmount`` (the
trailing identification-code extraction), including the "limit-number" chain
offset path (zkSync Lite / ImmutableX / dYdX). To eliminate any porting-error
risk, this test asserts ``_sdk_extract_trailing4`` reproduces the EXACT output
of the reference JS for 136 vectors generated by running the actual SDK code
via node — including the divergent limit-chain cases (e.g. zksync
``123456789010000`` -> ``8901`` via the validDigit offset, vs ``0000`` last-4).

Fixture: tests/fixtures/orbiter_ptext_reference.json (provenance inside).

Also pins the Wave-B over-degradation FIX: our Chain enum ``zksync`` is zkSync
ERA (full EVM), so an Orbiter deposit on zksync must DECODE via last-4, not be
degraded to None.
"""

from __future__ import annotations

import json
from pathlib import Path

from recupero.trace.orbiter import (
    _sdk_extract_trailing4,
    decode_orbiter_destination,
)

_FIXTURE = Path(__file__).parent / "fixtures" / "orbiter_ptext_reference.json"

# SDK chain name -> limit_max_bits (None = non-limit, last-4). Mirrors the
# MAX_BITS limit set in core.ts that drives isLimitNumber.
_SDK_CHAIN_LIMIT_BITS: dict[str, int | None] = {
    "eth": None,
    "arbitrum": None,
    "optimism": None,
    "polygon": None,
    "bnbchain": None,
    "zksync": 35,        # zkSync Lite (packed balance)
    "immutablex": 28,
    "dydx": 28,
}


def _load_vectors() -> list[dict]:
    data = json.loads(_FIXTURE.read_text(encoding="utf-8"))
    return data["vectors"]


def test_extraction_matches_reference_js_for_every_vector() -> None:
    """_sdk_extract_trailing4 reproduces the reference JS pText for all 136
    vectors (state False == our None; otherwise the exact 4-char string)."""
    vectors = _load_vectors()
    assert len(vectors) >= 130, "reference fixture unexpectedly small"
    mismatches: list[str] = []
    for v in vectors:
        chain = v["chain"]
        assert chain in _SDK_CHAIN_LIMIT_BITS, f"unmapped reference chain {chain}"
        bits = _SDK_CHAIN_LIMIT_BITS[chain]
        got = _sdk_extract_trailing4(v["amount"], limit_max_bits=bits)
        expected = v["pText"] if v["state"] else None
        if got != expected:
            mismatches.append(
                f"chain={chain} amount={v['amount']} bits={bits} "
                f"expected={expected!r} got={got!r}"
            )
    assert not mismatches, (
        "Python port diverges from the reference SDK JS:\n  "
        + "\n  ".join(mismatches)
    )


def test_limit_branch_is_actually_exercised() -> None:
    """Guard that the fixture contains genuinely divergent limit-chain rows
    (offset != last-4) — otherwise the equivalence test would be vacuous."""
    vectors = _load_vectors()
    divergent = 0
    by_amount: dict[str, dict[str, str | None]] = {}
    for v in vectors:
        by_amount.setdefault(v["amount"], {})[v["chain"]] = (
            v["pText"] if v["state"] else None
        )
    for _amt, by_chain in by_amount.items():
        eth = by_chain.get("eth")
        for c in ("zksync", "immutablex", "dydx"):
            if c in by_chain and by_chain[c] != eth:
                divergent += 1
    assert divergent >= 3, f"expected divergent limit rows, found {divergent}"


def test_zksync_era_source_now_decodes_not_degraded() -> None:
    """Over-degradation FIX: our enum 'zksync' is zkSync Era (full EVM), so an
    Orbiter deposit there decodes via last-4 (was wrongly None in Wave B)."""
    # 0.01 ETH bridged to Base (9021) deposited on zkSync Era.
    d = decode_orbiter_destination("10000000000009021", source_chain="zksync")
    assert d is not None
    assert d.code == 21
    assert d.our_chain == "base"
    # Also the other former-degraded synonyms behave as full-EVM now.
    assert decode_orbiter_destination("10000000000009002", source_chain="zksync_era") is not None


def test_true_limit_chain_uses_offset_path() -> None:
    """A genuine limit chain (zkSync Lite) with a divergent amount uses the
    validDigit offset, matching the SDK (123456789010000 -> 8901), whereas a
    full-EVM source would read last-4 (0000 -> rejected)."""
    # validDigit offset yields 8901 (not a 9xxx marker) -> None either way here,
    # but the EXTRACTION must differ; assert via the low-level helper.
    assert _sdk_extract_trailing4("123456789010000", limit_max_bits=35) == "8901"
    assert _sdk_extract_trailing4("123456789010000", limit_max_bits=None) == "0000"
