-- 007_case_tokens.sql
--
-- Token-gated customer portal access. Each case gets one or more
-- long-lived tokens that the victim can use to access their case
-- page at /portal/<token> without needing a username/password.
--
-- Why tokens (not email-link OTPs)?
-- The victim already has the diagnostic + engagement letter delivered
-- as email attachments — losing access to that mailbox means losing
-- access to those documents anyway. A bearer token in a magic link
-- is the same security model as the artifacts they already received.
-- TTL + revocation give us a kill-switch if a token is ever pasted
-- into a public Discord by an angry customer.
--
-- The portal is intentionally read-mostly (status + downloads +
-- engagement signature). No raw DB writes other than the
-- engagement_signatures audit trail.

CREATE TABLE IF NOT EXISTS public.case_tokens (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    case_id     uuid NOT NULL REFERENCES public.cases(id) ON DELETE CASCADE,

    -- The token value itself. 32 bytes base64url ≈ 43 chars.
    -- Generated by recupero.portal.tokens.generate_token().
    -- UNIQUE so we can look it up directly without a per-case scan.
    token       text NOT NULL UNIQUE,

    -- TTL. The default is 90 days from creation — long enough for
    -- the typical 30-day engagement + buffer for the victim to
    -- come back and re-download artifacts. Operator can extend by
    -- re-issuing a new token. NULL = never expires (rare; only
    -- for special-case enterprise victims with long workflows).
    created_at  timestamptz NOT NULL DEFAULT NOW(),
    expires_at  timestamptz,

    -- Manual kill switch. If set, the token is treated as invalid
    -- regardless of expires_at. Operator runs:
    --   UPDATE public.case_tokens SET revoked_at = NOW()
    --    WHERE token = '<value>';
    -- to revoke. We don't DELETE so the audit trail survives.
    revoked_at  timestamptz,

    -- Free-form note: who is this token for ('victim', 'attorney',
    -- 'family-member')? Surfaces on the operator's status page.
    label       text,

    -- Last time someone successfully accessed a portal route with
    -- this token. Useful for "is the victim engaged?" signals and
    -- for revoking idle tokens. NULL = never used.
    last_used_at timestamptz
);

CREATE INDEX IF NOT EXISTS case_tokens_case_id_idx
    ON public.case_tokens (case_id);

-- Partial index for the hot lookup path: token-by-value WHERE not revoked.
-- Most lookups will hit this; full scans of revoked tokens are rare.
CREATE INDEX IF NOT EXISTS case_tokens_active_token_idx
    ON public.case_tokens (token)
 WHERE revoked_at IS NULL;

COMMENT ON TABLE public.case_tokens IS
    'Bearer tokens for token-gated /portal/<token> customer access. '
    'See recupero.portal.tokens for the generation/verification logic.';
