"""Brief generator.

Reads one or more case.json files, a victim.json, and renders both:
  * Maple Finance compliance freeze request
  * Law enforcement handoff package

The two HTML files are written to data/cases/<primary_case>/briefs/.

Design notes:
  - The "primary case" is the victim's case (depth=1 from the victim).
  - "Linked cases" are subsequent depth-N traces that show forwarding hops.
  - We identify the "stolen asset" automatically: the largest USD-value
    transfer in the primary case is treated as the theft event.
  - The "current holder" is the destination of the LAST transfer in the
    forwarding chain that involved the stolen asset.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from datetime import UTC, datetime
from decimal import Decimal
from pathlib import Path
from typing import Any
from uuid import uuid4

from jinja2 import Environment, FileSystemLoader, select_autoescape

from recupero import __version__
from recupero.models import Case, Chain, Transfer
from recupero.reports.victim import VictimInfo

log = logging.getLogger(__name__)

TEMPLATES_DIR = Path(__file__).parent / "templates"


# Single source of truth for the freeze_brief.json schema version.
# Imported by emit_brief.py + the worker synthesizer so a future bump
# only happens here.
BRIEF_SCHEMA_VERSION = "0.16.4"

# Earliest version that wrote ALL the fields the current rendering
# chain expects (evidence_type, evidence_mode, etc.). Briefs from
# before this version trigger a stale-brief warning so operators
# know the rendering may use "currently held" language for what
# should be historical-receipt cases.
_MIN_RECOGNIZED_BRIEF_VERSION = "0.14.8"


def check_brief_schema_version(brief: dict[str, Any]) -> str | None:
    """Inspect brief.SCHEMA_VERSION. Returns None if the brief is
    current; returns a human-readable warning string if it's stale
    or missing the version stamp entirely.

    Callers should log the warning and surface it in the rendered
    output (banner, header note, etc.). The reader does NOT refuse
    to render — the brief may still be partially useful — but the
    caller now has the data to be honest about its provenance.
    """
    version = brief.get("SCHEMA_VERSION")
    # Warning strings use ASCII dashes (not em-dashes) so they render
    # correctly on Windows cp1252 stdout where operator logs are read.
    if version is None:
        return (
            f"Brief lacks SCHEMA_VERSION stamp -- generated by a pre-"
            f"v{BRIEF_SCHEMA_VERSION} pipeline. Some evidence-type / "
            "evidence_mode fields may be absent, causing the rendering "
            "to fall back to 'currently held' language even for "
            "historical-receipt cases. Re-emit the brief by running "
            "`recupero emit-brief <case_id>` against the latest "
            f"freeze_asks.json to get full v{_MIN_RECOGNIZED_BRIEF_VERSION}+ "
            "rendering."
        )
    # Both version strings are dot-separated "MAJOR.MINOR.PATCH". A
    # simple tuple comparison handles all cases we care about.
    def _as_tuple(s: str) -> tuple[int, ...]:
        try:
            return tuple(int(p) for p in s.split("."))
        except Exception:  # noqa: BLE001
            return (0, 0, 0)
    if _as_tuple(version) < _as_tuple(_MIN_RECOGNIZED_BRIEF_VERSION):
        return (
            f"Brief was generated by pipeline v{version}, which predates "
            f"v{_MIN_RECOGNIZED_BRIEF_VERSION}'s evidence-type fields. "
            f"Rendering may use 'currently held' language for historical-"
            f"receipt cases. Re-emit the brief for accurate framing."
        )
    return None


# Chain → address-page explorer URL prefix — centralized in
# src/recupero/_common.py.
from recupero._common import (
    ADDRESS_EXPLORER_BY_CHAIN as _ADDRESS_EXPLORER_BY_CHAIN,
    atomic_write_text,
    explorer_name_for_chain as _common_explorer_name_for_chain,
    short_addr as _short_addr,
)


def _address_explorer_url(address: str, chain: Chain | str | None) -> str:
    """Build a click-through URL for ``address`` on the chain explorer.

    v0.16.10 (round-9 output MEDIUM): for unknown chains return empty
    string instead of Etherscan-by-default. Pre-v0.16.10 a Solana /
    Tron / Bitcoin / future-chain address would get an etherscan.io
    link that 404s on click — compliance reviewers see "view on
    Etherscan" buttons that don't work, an impression of sloppy work.
    Templates already wrap explorer URLs in `{% if %}` so empty
    strings render gracefully (no link instead of broken link).
    """
    if not address:
        return ""
    chain_str = chain.value if isinstance(chain, Chain) else (chain or "")
    prefix = _ADDRESS_EXPLORER_BY_CHAIN.get(chain_str)
    if not prefix:
        return ""  # unknown chain → no link (template renders the address as text)
    return f"{prefix}{address}"


@dataclass
class InvestigatorInfo:
    name: str
    organization: str
    email: str
    phone: str | None = None


@dataclass
class IssuerInfo:
    """The entity that issued the stolen token. Used to address the freeze brief.

    For tokenized RWAs, the issuer is the entity with protocol-level control over
    the wrapper token (mint/burn) — i.e. the only party that can implement a
    technical freeze. For pure DeFi assets without an issuer, leave name empty
    and the brief skips the freeze-request section.
    """
    name: str                              # e.g. "Midas Software GmbH"
    short_name: str                        # e.g. "Midas" — used in filenames and prose
    contact_email: str                     # e.g. "team@midas.app"
    jurisdiction: str | None = None        # e.g. "Germany (EU)"
    regulatory_framework: str | None = None  # e.g. "MiCA, GDPR, BaFin oversight"
    secondary_party: str | None = None     # e.g. "Maple Finance" — copied on brief
    secondary_role: str | None = None      # e.g. "underlying strategy manager"
    asset_description: str | None = None   # one-line technical description of asset
    kyc_required: bool = False             # was KYC required to acquire the asset originally?
    kyc_minimum: str | None = None         # e.g. "$125,000 USD"


# Sensible default for the Zigha case (Midas-issued msyrupUSDp)
MIDAS_ISSUER = IssuerInfo(
    name="Midas Software GmbH",
    short_name="Midas",
    contact_email="team@midas.app",
    jurisdiction="Germany (European Union)",
    regulatory_framework="EU Markets in Crypto-Assets Regulation (MiCA), General Data Protection Regulation (GDPR), German federal financial supervision (BaFin)",
    secondary_party="Maple Finance",
    secondary_role="underlying yield strategy manager",
    asset_description="Midas-issued ERC-20 wrapper token representing a pre-deposit position in Maple Finance's syrupUSDT institutional credit strategy on the Plasma blockchain",
    kyc_required=True,
    kyc_minimum="USD 125,000",
)


@dataclass
class BriefBundle:
    """Both rendered briefs + their disk paths."""
    maple_html: str
    le_html: str
    maple_path: Path
    le_path: Path
    manifest_path: Path
    brief_id: str


# ---- Stolen-asset issuer resolution (v0.20.1) ---- #


def _resolve_theft_asset_issuer_name(
    theft_transfer: Transfer, *, fallback: str,
) -> str:
    """Resolve the actual issuer of the stolen token via the issuer DB.

    Pre-v0.20.1 the `asset.issuer` field in the freeze-letter context
    was set to the freeze-TARGET issuer (e.g., Tether for a downstream
    USDT freeze), which meant a freeze letter sent to Tether about
    USDT recoverable positions read "Asset issuer: Tether" in Section 2
    even when the originally-stolen token was msyrupUSDp issued by
    Midas. The two facts (what was stolen vs whom we're asking to
    freeze) are distinct and both belong on the letter.

    Falls back to ``fallback`` if no matching entry — preserves
    backward compatibility for cases where the stolen token isn't in
    the issuer DB.
    """
    try:
        from recupero._common import canonical_address_key as _ck
        from recupero.freeze.asks import load_issuer_db
        contract = theft_transfer.token.contract
        if not contract:
            return fallback
        db = load_issuer_db()
        canon = _ck(contract)
        entry = db.get((theft_transfer.chain, canon))
        if entry and entry.issuer:
            return entry.issuer
    except Exception as exc:  # noqa: BLE001
        log.warning(
            "could not resolve stolen-asset issuer for %s: %s — falling "
            "back to %s", theft_transfer.token.symbol, exc, fallback,
        )
    return fallback


# ---- Small generate_briefs helpers (v0.20.0 Phase C decomposition) ---- #


def _resolve_render_time() -> datetime:
    """Resolve the wall-clock-or-pinned render timestamp.

    Honors ``SOURCE_DATE_EPOCH`` for reproducible-builds workflows.
    On parse failure, falls back to ``datetime.now(UTC)``. v0.20.0
    Phase C extraction: previously inlined ~15 lines inside
    generate_briefs() with two ad-hoc imports; clarified into a
    single pure helper.
    """
    import os
    src_epoch = os.environ.get("SOURCE_DATE_EPOCH", "").strip()
    if src_epoch:
        try:
            return datetime.fromtimestamp(int(src_epoch), tz=UTC)
        except (ValueError, TypeError):
            log.warning(
                "SOURCE_DATE_EPOCH=%r is not a valid integer epoch; "
                "falling back to wall-clock", src_epoch,
            )
    return datetime.now(UTC)


def _make_brief_id(case_id: str, theft_tx_hash: str) -> str:
    """Deterministic brief identifier.

    v0.16.7 (round-9 output-artifacts CRIT): pre-v0.16.7 brief_id was
    `f"BRIEF-{wall_clock}-{uuid4().hex[:6]}"`, which made PDFs and
    HTML artifacts non-reproducible — re-running the same case
    produced different bytes (filename, cover-page text, footer code).
    Chain-of-custody hash verification was therefore impossible.

    The fix: derive brief_id deterministically from case content
    (case_id + earliest theft_transfer hash). Two renders of the same
    case → same brief_id → byte-reproducible artifacts.

    v0.20.0 Phase C extraction: moved out of generate_briefs() body
    into a pure helper so the rationale lives next to the algorithm
    instead of as a 17-line inline comment block in an orchestrator.
    """
    import hashlib
    seed = f"{case_id}|{theft_tx_hash}"
    suffix = hashlib.sha256(seed.encode("utf-8")).hexdigest()[:6]
    return f"BRIEF-{case_id[:8]}-{suffix}"


def generate_briefs(
    *,
    primary_case: Case,
    linked_cases: list[Case],
    victim: VictimInfo,
    investigator: InvestigatorInfo,
    case_dir: Path,
    issuer: IssuerInfo = MIDAS_ISSUER,
    asset_type: str = "ERC-20 yield-bearing wrapper token",
    asset_usd_value_current: str | None = None,
    outbound_count_of_stolen_asset: int = 0,
    flow_filename: str | None = None,
    issuer_freezable: dict | None = None,
    # v0.18.6 (round-11 PDF-CRIT-006): IC3 case ID flows through
    # editorial JSON (cases.ic3_case_id captured at intake) but was
    # never wired into the LE handoff. Operators curate it specifically
    # so FBI can cross-reference the IC3 record; pre-v0.18.6 the
    # handoff dropped it entirely.
    ic3_case_id: str | None = None,
    draft: bool = False,
    draft_label: str | None = None,
) -> BriefBundle:
    """Render both briefs and write them to disk.

    ``issuer_freezable`` (added 2026-05-15 in response to the
    operator-quality review on case e917ffc5) is the per-issuer
    FREEZABLE entry from ``freeze_brief.json``. When provided, the
    template renders an issuer-specific "current location + ask"
    that lists each holding (status FREEZABLE or INVESTIGATE) the
    issuer actually controls, instead of generically asking every
    issuer to freeze the original ETH at the first hop.

    Shape (matches freeze_brief.json):

      {
        "issuer": "Circle",
        "token": "USDC",
        "total_usd": "$7,097.58",
        "total_suspected_usd": "$1,037,451.35",
        "freeze_capability": "HIGH",
        "holdings": [
          {"address": "0xABC...",
           "amount": "1066.27 USDC",
           "usd": "$1,066.27",
           "status": "FREEZABLE"},
          ...
        ],
        ...
      }

    When None (the legacy/wallet-trace path), the template falls
    back to single-asset/single-holder rendering using
    ``theft_transfer`` as the source. Backward-compatible for any
    caller that hasn't yet been updated to pass per-issuer data.
    """
    # Identify the theft event(s). _find_theft_events returns the full
    # drain cluster (primary event first, then any others within the
    # 7-day window). For real-world cases drained across multiple
    # transactions, this surfaces the full timeline in the LE handoff
    # while keeping the freeze letter focused on the primary event.
    theft_events = _find_theft_events(primary_case)
    if not theft_events:
        raise ValueError(
            f"No transfers in case {primary_case.case_id} could be identified as the theft event."
        )
    theft_transfer = theft_events[0]  # primary (headline) event

    # Build the forwarding chain across linked cases.
    # v0.17.2 (POLISH-3): also build the full fan-out tree so the LE
    # handoff template can render every dispersal branch, not just
    # the primary linear chain. The legacy `hops` field is kept for
    # back-compat with v0.16.x templates; new templates should consume
    # `hops_tree` for the complete picture.
    hops = _build_hops(theft_transfer, linked_cases)
    hops_tree = _build_hop_tree(theft_transfer, linked_cases)

    # v0.20.2 (audit-round-3 R3-12): track the per-hop chain on the
    # current_holder, not just the address. On a cross-chain trail
    # (ETH drain → bridge → Tron USDT), `hops[-1].chain` may differ
    # from `primary_case.chain`. Pre-v0.20.2 the
    # current_holder.explorer_url was always built from
    # primary_case.chain — so a Tron current-holder linked to
    # etherscan/404. Now we route the explorer URL through the
    # actual chain of the final hop.
    if hops:
        current_holder_addr = hops[-1].to_address
        current_holder_chain = hops[-1].chain
    else:
        current_holder_addr = theft_transfer.to_address
        current_holder_chain = theft_transfer.chain

    # Identify wallets across all cases for the LE summary table
    identified_wallets = _build_identified_wallets(primary_case, linked_cases, victim, current_holder_addr)

    # Common context. v0.20.0 Phase C: render-time + deterministic
    # brief-id resolution extracted to small pure helpers above. The
    # rationale + reproducible-builds contract live with the helpers
    # so the orchestrator can read as orchestration.
    now = _resolve_render_time()
    brief_id = _make_brief_id(primary_case.case_id, theft_transfer.tx_hash)

    ctx: dict[str, Any] = {
        "case_id": primary_case.case_id,
        "brief_id": brief_id,
        # v0.18.6: IC3 reference + DRAFT watermark plumbed into ctx.
        "ic3_case_id": ic3_case_id,
        "draft": draft,
        "draft_label": draft_label or "DRAFT",
        # v0.19.1 (round-12 PDF-CRIT-4): the 23 templates that render this
        # field already append a literal " UTC" suffix. Pre-v0.19.1 the
        # value carried a trailing 'Z', producing "2026-05-19T17:00:00Z UTC"
        # on every cover page + footer + section header — stuttered
        # timestamp on legal documents reads as templated/broken to LE
        # and lawyers. Strip the 'Z'; templates own the UTC marker.
        "generated_at": now.strftime("%Y-%m-%dT%H:%M:%S"),
        "verified_at": now.strftime("%Y-%m-%d"),
        # v0.17.4 (round-10 audit HIGH): primary_chain populated for the
        # LE handoff template. Pre-v0.17.4 the template's
        # `{{ primary_chain | default("Ethereum") }}` silently rendered
        # "Ethereum" for every Solana/Tron/BSC theft, putting a wrong-
        # chain attestation on the cover page of every non-ETH brief.
        # v0.18.6 (round-11 PDF-HIGH-010): use emit_brief's display-name
        # map so "bsc" → "BNB Chain" instead of `.capitalize()` =
        # "Bsc". Pre-v0.18.6 the LE handoff cover for a BSC case
        # printed "USDT on Bsc"; the trace report for the same case
        # printed "BNB Chain". Inconsistent + unprofessional.
        "primary_chain": _resolve_primary_chain_display(primary_case),
        # v0.20.2 (audit-round-3 R3-9/R3-10): canonical block-
        # explorer display name for the case chain, so letter prose
        # can render "View on Tronscan" on a Tron case instead of
        # the hard-coded "View on Etherscan" that was rendering
        # alongside Tronscan URLs. Centralized in _common; templates
        # use `{{ primary_chain_explorer_name }}` (with safe
        # defaults).
        "primary_chain_explorer_name": _common_explorer_name_for_chain(
            primary_case.chain,
        ),
        "trace_started_at": (
            primary_case.trace_started_at.strftime("%Y-%m-%dT%H:%M:%SZ")
            if primary_case.trace_started_at else None
        ),
        "software_version": __version__,
        "victim": victim.model_dump(),
        "investigator": investigator.__dict__,
        "asset": {
            "symbol": theft_transfer.token.symbol,
            "contract": theft_transfer.token.contract or "(native)",
            # v0.20.1 (Jacob V-CFI01 residual #6): "issuer" on the
            # asset block reflects the STOLEN-TOKEN's actual issuer
            # (resolved from the issuer DB via contract address), NOT
            # the freeze-target issuer. Pre-v0.20.1 these were
            # conflated: a Tether-targeted freeze letter for an
            # mSyrupUSDp theft labeled "Asset issuer: Tether" even
            # though mSyrupUSDp is issued by Midas. Section 2 of the
            # letter now reads "Asset issuer: Midas" while the rest
            # of the letter correctly targets Tether for the downstream
            # USDT freeze. Both facts coexist; neither overwrites the
            # other.
            "issuer": _resolve_theft_asset_issuer_name(
                theft_transfer, fallback=issuer.name,
            ),
            "issuer_short": issuer.short_name,
            "type": asset_type,
            "description": issuer.asset_description or asset_type,
            "amount_human": _fmt_decimal(theft_transfer.amount_decimal),
            "usd_value_at_theft": _fmt_usd(theft_transfer.usd_value_at_tx),
            # v0.20.2 (audit-round-3 R3-3): expose aggregate
            # across all theft_events so the headline asset block
            # renders the TOTAL stolen value on multi-event drains
            # (e.g., V-CFI01 shape: 6 × $600K = $3.6M). The
            # `usd_value_at_theft` field stays as the primary
            # event's USD (back-compat for callers that depend on
            # the single-event semantics); templates that want
            # the multi-event headline use `total_usd_value_at_theft`.
            "total_usd_value_at_theft": _fmt_usd(
                sum(
                    (t.usd_value_at_tx for t in theft_events
                     if t.usd_value_at_tx is not None),
                    start=Decimal(0),
                ) or theft_transfer.usd_value_at_tx,
            ),
            "total_amount_human": _fmt_decimal(
                sum(
                    (t.amount_decimal for t in theft_events
                     if t.amount_decimal is not None),
                    start=Decimal(0),
                ) or theft_transfer.amount_decimal,
            ),
            "theft_event_count": len(theft_events),
            "is_multi_event": len(theft_events) > 1,
            "usd_value_current": asset_usd_value_current,
        },
        "issuer": {
            "name": issuer.name,
            "short_name": issuer.short_name,
            "contact_email": issuer.contact_email,
            "jurisdiction": issuer.jurisdiction,
            "regulatory_framework": issuer.regulatory_framework,
            "secondary_party": issuer.secondary_party,
            "secondary_role": issuer.secondary_role,
            "kyc_required": issuer.kyc_required,
            "kyc_minimum": issuer.kyc_minimum,
        },
        # Address URLs are computed per-row so every raw address shown
        # in the letter is a click-through link in the rendered PDF.
        # WeasyPrint converts <a href=".."> annotations into PDF link
        # rectangles, so compliance reviewers can jump straight from
        # the document to the on-chain record.
        "theft_event": {
            "tx_hash": theft_transfer.tx_hash,
            "block_number": theft_transfer.block_number,
            "timestamp_human": theft_transfer.block_time.strftime("%Y-%m-%d %H:%M:%S"),
            "from_address": theft_transfer.from_address,
            "to_address": theft_transfer.to_address,
            "explorer_url": theft_transfer.explorer_url,
            "from_explorer_url": _address_explorer_url(
                theft_transfer.from_address, theft_transfer.chain
            ),
            "to_explorer_url": _address_explorer_url(
                theft_transfer.to_address, theft_transfer.chain
            ),
        },
        # Full theft-event cluster, sorted by block_time ascending for
        # chronological rendering in section 3 of the LE handoff.
        # The primary event is at index 0 unless block_time orders it
        # later; templates that want strictly chronological should sort.
        # ``theft_event_count`` and ``theft_event_total_usd`` are
        # convenience aggregates for prose generation.
        "theft_events": [
            {
                "tx_hash": t.tx_hash,
                "block_number": t.block_number,
                "timestamp_human": t.block_time.strftime("%Y-%m-%d %H:%M:%S"),
                "from_address": t.from_address,
                "to_address": t.to_address,
                "amount_human": _fmt_decimal(t.amount_decimal),
                "symbol": t.token.symbol,
                "usd_value": _fmt_usd(t.usd_value_at_tx),
                "explorer_url": t.explorer_url,
                "from_explorer_url": _address_explorer_url(t.from_address, t.chain),
                "to_explorer_url": _address_explorer_url(t.to_address, t.chain),
                "is_primary": t.transfer_id == theft_transfer.transfer_id,
            }
            for t in sorted(theft_events, key=lambda x: x.block_time)
        ],
        "theft_event_count": len(theft_events),
        "theft_event_total_usd": _fmt_usd(
            sum(
                (t.usd_value_at_tx for t in theft_events
                 if t.usd_value_at_tx is not None),
                start=Decimal(0),
            )
        ),
        "hops": [
            {
                "tx_hash": h.tx_hash,
                "timestamp_human": h.block_time.strftime("%Y-%m-%d %H:%M:%S"),
                "from_address": h.from_address,
                "to_address": h.to_address,
                "amount_human": _fmt_decimal(h.amount_decimal),
                "symbol": h.token.symbol,
                "explorer_url": h.explorer_url,
                "from_explorer_url": _address_explorer_url(h.from_address, h.chain),
                "to_explorer_url": _address_explorer_url(h.to_address, h.chain),
            }
            for h in hops
        ],
        # v0.17.2 (POLISH-3): full fan-out tree exposed for templates
        # that want to render every dispersal branch. Each entry carries
        # the same shape as `hops` entries plus `usd_value` for
        # USD-rank-aware sorting in the template.
        "hops_tree": [
            {
                "tx_hash": h.tx_hash,
                "timestamp_human": h.block_time.strftime("%Y-%m-%d %H:%M:%S"),
                "from_address": h.from_address,
                "to_address": h.to_address,
                "amount_human": _fmt_decimal(h.amount_decimal),
                "symbol": h.token.symbol,
                "usd_value": (
                    f"${h.usd_value_at_tx:,.2f}"
                    if h.usd_value_at_tx is not None else None
                ),
                "explorer_url": h.explorer_url,
                "from_explorer_url": _address_explorer_url(h.from_address, h.chain),
                "to_explorer_url": _address_explorer_url(h.to_address, h.chain),
            }
            for h in hops_tree
        ],
        "hops_tree_branch_count": len(hops_tree),
        "hops_tree_has_fanout": len(hops_tree) > len(hops),
        # v0.20.1 (Jacob V-CFI01 residual #3): "forwarding_observed"
        # is True whenever we have ANY evidence of downstream movement,
        # including fan-out branches OR per-issuer freezable holdings
        # (which represent received-from-perp downstream addresses).
        # Pre-v0.20.1 the freeze-letter template gated Section 3's "no
        # forwarding observed" stub solely on `hops` — for cases where
        # the linear hop chain is empty but the issuer freezable list
        # has downstream wallets, the stub printed contradicting
        # Section 4 (which listed those wallets).
        "forwarding_observed": bool(
            hops
            or len(hops_tree) > 0
            or (
                issuer_freezable
                and isinstance(issuer_freezable, dict)
                and issuer_freezable.get("holdings")
            )
        ),
        "current_holder": {
            "address": current_holder_addr,
            # v0.20.2 (audit-round-3 R3-12): per-hop chain so a
            # cross-chain current-holder (e.g., Tron USDT after a
            # bridge) links to the right block explorer instead of
            # always-etherscan.
            "explorer_url": _address_explorer_url(
                current_holder_addr, current_holder_chain,
            ),
        },
        # Asset contract address: clickable token-contract page when
        # the contract is known (None for native ETH / BTC).
        "asset_contract_explorer_url": (
            _address_explorer_url(theft_transfer.token.contract,
                                  theft_transfer.chain)
            if theft_transfer.token.contract else None
        ),
        # Victim wallet — first interaction many compliance reviewers
        # will want is to verify the seed wallet on chain.
        "victim_wallet_explorer_url": _address_explorer_url(
            victim.wallet_address, primary_case.chain
        ),
        "outbound_count_of_stolen_asset": outbound_count_of_stolen_asset,
        "identified_wallets": identified_wallets,
        # Fund-flow diagram lives in briefs/flow_<hash>.svg as a
        # standalone artifact. Letters reference it via attachment-
        # pointer in section 3 (no inline embed — the inline version
        # was unreadable when recipients re-printed the letter to
        # PDF). Templates guard with ``{% if flow_filename %}``.
        "flow_filename": flow_filename,
        # Per-issuer freezable holdings — see docstring above.
        # Pre-rendered for the template via ``_build_issuer_freezable_ctx``
        # so the template doesn't have to know about freeze_brief.json
        # internals or compute explorer URLs.
        "issuer_freezable": _build_issuer_freezable_ctx(
            issuer_freezable, primary_case.chain,
        ),
        # Law-enforcement filing-route recommendation. Only the LE
        # template uses this; the issuer freeze letter ignores the
        # ``le_routing`` context key. Built from victim's state +
        # country + (approximate) total loss so the LE handoff names
        # specific filing channels (IC3 + state AG + escalation tiers).
        #
        # v0.20.2 (audit-round-2 finding #4): LE-routing thresholds
        # (IC3-only / state-AG / multi-jurisdiction escalation) are
        # driven by TOTAL loss, not just the primary theft event.
        # Pre-v0.20.2 we passed `theft_transfer.usd_value_at_tx` —
        # in a V-CFI01-shape case the drain is split across N
        # transactions (e.g. 6 × $600K = $3.6M total), and using the
        # primary alone routed the case to the wrong tier and
        # understated severity in the LE handoff narrative.
        "le_routing": _build_le_routing_ctx(
            victim,
            sum(
                (t.usd_value_at_tx for t in theft_events
                 if t.usd_value_at_tx is not None),
                start=Decimal(0),
            ) or theft_transfer.usd_value_at_tx,
        ),
    }

    env = Environment(
        loader=FileSystemLoader(TEMPLATES_DIR),
        autoescape=select_autoescape(["html", "j2"]),
        trim_blocks=True,
        lstrip_blocks=True,
    )
    # v0.17.2 (output polish POLISH-4): pluralization filter so
    # templates can write `{{ n }} {{ n | pluralize("transfer") }}`
    # and get "1 transfer" / "2 transfers" without manual ternaries.
    # The 2-arg form lets callers override the plural ending for
    # irregular nouns: `{{ n | pluralize("hop", "hops") }}`.
    env.filters["pluralize"] = _pluralize_filter

    issuer_template = "issuer_freeze_request.html.j2"
    # The legacy maple.html.j2 hardcodes "is currently held in"
    # language without evidence_mode branching — falling back to it
    # would render false claims on historical-receipt cases. Refuse
    # the fallback; a missing modern template is a deploy-config bug
    # to surface, not paper over.
    try:
        env.get_template(issuer_template)
    except Exception as _exc:  # noqa: BLE001
        raise RuntimeError(
            f"issuer_freeze_request.html.j2 template missing — refusing "
            f"to fall back to maple.html.j2 which lacks evidence_mode "
            f"branching and could render false 'currently held' claims "
            f"on historical-receipt cases. Underlying error: {_exc!r}"
        ) from _exc

    maple_html = env.get_template(issuer_template).render(**ctx)
    le_html = env.get_template("le.html.j2").render(**ctx)

    briefs_dir = case_dir / "briefs"
    briefs_dir.mkdir(parents=True, exist_ok=True)
    issuer_slug = (issuer.short_name or "issuer").lower().replace(" ", "_")
    maple_path = briefs_dir / f"freeze_request_{issuer_slug}_{brief_id}.html"
    # Include the issuer slug in the LE handoff filename too — the LE
    # template references issuer.name / issuer.short_name extensively
    # (preservation requests, KYC framing, secondary-party language),
    # so multi-issuer cases produce DIFFERENT le_handoff content per
    # call. Without the slug, generate_briefs called N times would
    # silently overwrite the previous LE handoff with the last issuer's
    # version. Per-issuer filename preserves all of them.
    le_path = briefs_dir / f"le_handoff_{issuer_slug}_{brief_id}.html"
    # v0.16.8 (round-9 output-artifacts HIGH): atomic writes via
    # tempfile+os.replace. Pre-v0.16.8 these were direct `write_text`
    # calls — a worker crash between writing maple_html and the
    # manifest left an HTML on disk with no manifest pointer, and a
    # concurrent bucket sync could pick up a half-written file on
    # large multi-MB renders. The atomic-write helper guarantees the
    # bucket either sees the previous version or the new one in full.
    atomic_write_text(maple_path, maple_html)
    atomic_write_text(le_path, le_html)

    # v0.16.10 (round-9 output-artifacts MEDIUM): SHA256 of each output
    # in the manifest. Tamper-detection now works WITHOUT re-fetching
    # the bytes from the bucket — a chain-of-custody verifier can read
    # manifest.json, hash the local files, and compare. Hex-encoded
    # SHA256 (64 chars) per file.
    import hashlib
    maple_hash = hashlib.sha256(maple_html.encode("utf-8")).hexdigest()
    le_hash = hashlib.sha256(le_html.encode("utf-8")).hexdigest()

    manifest = {
        "brief_id": brief_id,
        "generated_at": now.isoformat(),
        "primary_case": primary_case.case_id,
        "linked_cases": [c.case_id for c in linked_cases],
        "theft_tx": theft_transfer.tx_hash,
        "current_holder": current_holder_addr,
        "victim_name": victim.name,
        "investigator": investigator.__dict__,
        "issuer": issuer.name,
        "software_version": __version__,
        "outputs": {
            "issuer_freeze_request": str(maple_path),
            "le_handoff": str(le_path),
        },
        "output_sha256": {
            "issuer_freeze_request": maple_hash,
            "le_handoff": le_hash,
        },
    }
    manifest_path = briefs_dir / f"manifest_{brief_id}.json"
    # Atomic — see comment on maple/le writes above.
    atomic_write_text(manifest_path, json.dumps(manifest, indent=2))

    log.info("wrote issuer freeze request: %s", maple_path)
    log.info("wrote LE handoff: %s", le_path)

    return BriefBundle(
        maple_html=maple_html,
        le_html=le_html,
        maple_path=maple_path,
        le_path=le_path,
        manifest_path=manifest_path,
        brief_id=brief_id,
    )


# ---------- internals ----------


def _find_theft_transfer(case: Case) -> Transfer | None:
    """The primary theft event — the highest-USD transfer in the
    drain cluster. Backward-compat wrapper around
    ``_find_theft_events``; returns the first (largest-by-USD) item.

    Most letter sections render this single transfer as the headline
    "Theft Event". Section 3 of the LE handoff additionally renders
    the full cluster from ``_find_theft_events`` when the drain
    spans multiple transactions.
    """
    events = _find_theft_events(case)
    return events[0] if events else None


def _find_theft_events(
    case: Case,
    *,
    time_window_hours: int = 168,
) -> list[Transfer]:
    """Find every transfer that looks like part of the drain.

    Real victims are often drained across multiple transactions —
    e.g., a phishing attack that approves a token's spender contract
    and then drains $X in piece-meal trades over hours, or a wallet
    that's slowly emptied as the perpetrator avoids triggering
    exchange-side monitoring thresholds. Before this function, the
    brief rendered ONE event (the biggest), implying a single
    theft; the letter prose said "$X was stolen on day Y", missing
    the actual story of "$X was stolen across N transactions on
    days Y through Y+3".

    Algorithm
    ---------

    1. Identify the largest-USD transfer in the case (the primary
       theft event). Same logic as the legacy single-event picker.
    2. Cluster around it: include every other transfer with
       ``block_time`` within ``time_window_hours`` of the primary
       event's block_time. The default window (168 hours / 7 days)
       is conservative — most drain campaigns wrap in under a week.
    3. Return the cluster ordered by block_time ascending (so the
       template can render them chronologically).

    Notes
    -----
    * Only outbound transfers from the seed (victim) address count
      as theft events. Internal-to-internal transfers (e.g., the
      perpetrator moving funds around) are part of the
      ``hops`` chain, not the theft events.
    * Returns the primary event first in the returned list (which
      may not be chronologically first), so callers reading
      ``events[0]`` get the headline. The chronological ordering is
      via ``sorted(events, key=block_time)`` if needed for the
      timeline render.
    * Empty list if no transfers at all in the case (wallet trace
      that returned nothing).

    Returns
    -------
    A list ordered with the primary event first, then all other
    events in the cluster sorted by block_time ascending. Empty
    list if no transfers in the case.
    """
    if not case.transfers:
        return []

    from recupero._common import canonical_address_key as _ck
    seed_lower = _ck(case.seed_address)

    # Outbound transfers from the victim
    outbound = [
        t for t in case.transfers
        if _ck(t.from_address) == seed_lower
    ]
    if not outbound:
        # Fallback: any transfer in the case (preserves legacy
        # behavior for cases where the seed_address normalization
        # diverges or the case has no direct-from-seed transfers).
        outbound = list(case.transfers)

    # Primary event: highest-USD with sensible fallback.
    #
    # v0.18.0 (round-11 forensic-CRIT-005): pre-v0.18.0 the unpriced
    # fallback was `max(outbound, key=amount_decimal)` — which compares
    # raw token-amount values across different tokens. Result: a
    # 1,000,000,000,000-token shitcoin transfer was picked as "primary
    # theft event" over a 1 ETH transfer, because Decimal compares the
    # numeric value of amount_decimal regardless of what token it is.
    # The LE handoff cover then claimed the headline theft was a
    # billion-shitcoin transfer instead of the real $3K ETH theft.
    #
    # New behavior:
    #   1. Prefer priced transfers (still picks max USD).
    #   2. Unpriced fallback: prefer NATIVE-asset transfers first (ETH,
    #      BNB, SOL, etc.) since those are typically real currency; among
    #      those pick the largest. Then known stablecoins (USDC, USDT,
    #      DAI). Then everything else by recency (most-recent first).
    #   3. Final fallback: first by block_time ascending (oldest first).
    #
    # The result is operationally never wrong — if priced data exists
    # at all, the USD ranking dominates. The unpriced fallback is a
    # last-resort heuristic and we surface it via a `log.warning`.
    priced = [t for t in outbound if t.usd_value_at_tx is not None]
    if priced:
        primary = max(priced, key=lambda t: t.usd_value_at_tx)
    else:
        _NATIVE_SYMBOLS = {"ETH", "BNB", "SOL", "TRX", "BTC", "POL", "MATIC", "AVAX"}
        _STABLE_SYMBOLS = {"USDC", "USDT", "DAI", "BUSD", "FDUSD", "TUSD", "USDP", "USDE", "USDe", "PYUSD"}

        def _rank_key(t):
            sym = (t.token.symbol or "").upper()
            if sym in _NATIVE_SYMBOLS:
                tier = 0
            elif sym in _STABLE_SYMBOLS:
                tier = 1
            else:
                tier = 2
            # Within tier, prefer larger amount_decimal but the
            # comparison is now within a SINGLE token class (native,
            # stablecoin, or other). Negate so max() picks the largest.
            return (tier, -float(t.amount_decimal or 0), t.block_time)

        primary = min(outbound, key=_rank_key, default=None)
        if primary is not None:
            log.warning(
                "_find_theft_events: no transfer carried usd_value_at_tx; "
                "picked primary by token-class fallback (sym=%s, "
                "amount=%s, tx=%s). Pricing failure upstream — verify "
                "the brief's headline before LE handoff.",
                primary.token.symbol, primary.amount_decimal, primary.tx_hash,
            )
    if primary is None:
        return []

    # Cluster around the primary event's block_time
    from datetime import timedelta
    window = timedelta(hours=time_window_hours)
    primary_time = primary.block_time

    cluster = [
        t for t in outbound
        if abs(t.block_time - primary_time) <= window
        and t.transfer_id != primary.transfer_id
    ]

    # Sort cluster by block_time ascending; prepend primary so
    # callers reading [0] get the headline event consistently
    cluster.sort(key=lambda t: t.block_time)
    return [primary] + cluster


def _pluralize_filter(n: int, singular: str, plural: str | None = None) -> str:
    """Jinja filter: return singular or plural noun based on count.

    Usage in templates:
      {{ n }} {{ n | pluralize("transfer") }}        -> "1 transfer" / "2 transfers"
      {{ n }} {{ n | pluralize("hop", "hops") }}     -> "1 hop"      / "2 hops"
      {{ n }} {{ n | pluralize("address", "addresses") }}

    Auto-pluralization adds "s" when plural is None. Pass the explicit
    plural form for irregular nouns ("addresses", "criteria", etc.).
    v0.17.2 (output polish POLISH-4).
    """
    try:
        count = int(n)
    except (TypeError, ValueError):
        return singular
    if count == 1:
        return singular
    return plural if plural is not None else singular + "s"


_BASE58_CHAINS: frozenset[Chain] = frozenset({
    Chain.solana,
    Chain.tron,
    Chain.bitcoin,
})


def _hop_addr_key(chain: Chain, address: str) -> str:
    """Chain-aware key for the hop-builder visited set + index.

    EVM hex addresses are lowercased (case-insensitive). Base58 addresses
    (Solana/Tron/Bitcoin) preserve case — lowercasing them produced invalid
    keys and let `_build_hops` infinite-loop on a case mismatch in v0.16.6.
    Token contracts always lowercased (EVM-only namespace).
    """
    if chain in _BASE58_CHAINS:
        return address
    return address.lower()


def _build_hops(theft: Transfer, linked_cases: list[Case]) -> list[Transfer]:
    """Find subsequent transfers of the stolen asset across linked cases.

    Walks forward picking the EARLIEST forwarding tx at each step
    (the natural primary chain). Returns the primary linear path
    only; callers that want the full fan-out should use
    ``_build_hop_tree`` instead. This signature is kept for
    backward compatibility with existing template renders that
    read a flat `hops` list.
    """
    tree = _build_hop_tree(theft, linked_cases)
    return _flatten_primary_chain(tree)


def _build_hop_tree(
    theft: Transfer,
    linked_cases: list[Case],
    *,
    max_branches_per_node: int = 5,
    max_depth: int = 6,
) -> list[Transfer]:
    """Build the full fan-out tree of subsequent transfers.

    v0.16.11 (round-9 output-artifacts HIGH): pre-v0.16.11 the hop
    builder walked ONLY the earliest forwarding tx at each step,
    silently dropping all sibling forwards. Real perpetrator wallets
    routinely split funds to N downstream addresses (the dispersal
    pattern); rendering just one branch under-reports the forwarding
    fan-out and misses subpoena targets that the LE handoff should
    name.

    The tree is returned flat (depth-first traversal) so existing
    callers iterating `hops` still see all transfers, BUT each
    transfer carries enough information (via `hop_depth` +
    `parent_transfer_id`) for templates to render a tree if they
    want to.

    Bounds: `max_branches_per_node` (5) keeps the brief readable;
    `max_depth` (6) prevents pathological deep-chain exploration.
    Both are well above typical real-case fan-out.
    """
    flat: list[Transfer] = []
    target_chain = theft.token.chain
    target_token_contract = (theft.token.contract or "").lower()
    start_key = _hop_addr_key(target_chain, theft.to_address)

    # Build a quick index: {(from_addr_key, token_contract_lower) -> list[Transfer]}
    # from_addr_key uses chain-aware normalization (base58 preserves case).
    index: dict[tuple[str, str], list[Transfer]] = {}
    for c in linked_cases:
        for t in c.transfers:
            if t.token.chain != target_chain:
                continue
            key = (_hop_addr_key(target_chain, t.from_address),
                   (t.token.contract or "").lower())
            index.setdefault(key, []).append(t)

    # DFS with visited-set to prevent cycles. Each branch contributes
    # up to `max_branches_per_node` transfers per source address;
    # USD-ranked so the highest-value branches are kept on tight caps.
    visited: set[str] = {start_key}

    def _walk(addr_key: str, depth: int) -> None:
        if depth >= max_depth:
            return
        candidates = list(index.get((addr_key, target_token_contract), []))
        if not candidates:
            return
        # Rank by (USD desc, block_number asc) — biggest moves first,
        # ties broken by chronology. The "primary" branch a template
        # picks for the linear-chain summary is candidates[0] post-sort.
        candidates.sort(
            key=lambda t: (
                -(float(t.usd_value_at_tx or 0)),
                t.block_number,
            ),
        )
        for next_hop in candidates[:max_branches_per_node]:
            next_key = _hop_addr_key(target_chain, next_hop.to_address)
            if next_key in visited:
                # Cycle. Don't recurse but still surface the edge —
                # the brief should show that the chain re-converges.
                flat.append(next_hop)
                continue
            visited.add(next_key)
            flat.append(next_hop)
            _walk(next_key, depth + 1)

    _walk(start_key, 0)
    return flat


def _flatten_primary_chain(tree: list[Transfer]) -> list[Transfer]:
    """Pick the PRIMARY linear chain (earliest forwarding tx at each
    step) from the full DFS-flattened tree.

    Backward-compatible with the pre-v0.16.11 `_build_hops` return
    value: a single linear path. Templates that want the fan-out
    should use `_build_hop_tree` directly.

    The DFS in `_build_hop_tree` rank-sorts candidates by USD desc;
    the primary chain follows the BIGGEST move at each node. That's
    the headline-amount path, which matches what compliance teams
    want to see in section 2 of the freeze letter.
    """
    if not tree:
        return []
    # The primary chain is the first transfer at each new from-address
    # in DFS order. Walk the flat tree and keep the first hit per
    # source address.
    seen_sources: set[str] = set()
    primary: list[Transfer] = []
    for t in tree:
        from_l = (t.from_address or "").lower()
        if from_l in seen_sources:
            continue
        seen_sources.add(from_l)
        primary.append(t)
    return primary


def _build_identified_wallets(
    primary: Case,
    linked: list[Case],
    victim: VictimInfo,
    current_holder: str,
) -> list[dict[str, Any]]:
    """Collect every distinct address mentioned across all cases, with role + label."""
    seen: dict[str, dict[str, Any]] = {}

    # Each identified wallet carries an ``explorer_url`` so the
    # rendered table makes every address a click-through to its
    # on-chain page.
    #
    # v0.20.2 (audit-round-3 R3-5): per-row chain — pre-v0.20.2 we
    # used `primary.chain` for every row. On a cross-chain trace
    # (e.g., ETH drain → bridge → Tron USDT), every Tron / Solana
    # / Bitcoin address linked to ``etherscan.io/address/<base58>``
    # → 404. We now track the chain of the transfer where each
    # address was first seen and pass it through to
    # _address_explorer_url, so the dispatcher renders the right
    # block explorer for each row.
    primary_chain = primary.chain

    from recupero._common import canonical_address_key as _ck

    def _add(
        addr: str, role: str, type_str: str, notes: str,
        row_class: str = "", chain: Any = None,
    ):
        # v0.20.2 (audit-round-2 finding #7): canonical-key dedup
        # so base58 chains (Solana / Tron / Bitcoin) aren't silently
        # corrupted by `.lower()`. EVM addresses still collapse case
        # variants; base58 case is preserved (it's significant
        # on-chain). Aligns this routine with the rest of the
        # codebase post-v0.17.5.
        key = _ck(addr)
        if key in seen:
            # Don't downgrade — first observation wins for role/notes
            return
        row_chain = chain if chain is not None else primary_chain
        seen[key] = {
            "address": addr, "role": role, "type": type_str,
            "notes": notes, "row_class": row_class,
            "explorer_url": _address_explorer_url(addr, row_chain),
        }

    _add(
        victim.wallet_address, "Victim", "EOA",
        "Source of stolen funds", "victim-row",
        chain=primary_chain,  # victim wallet always on primary case chain
    )

    victim_key = _ck(victim.wallet_address)
    current_holder_key = _ck(current_holder)
    for c in [primary, *linked]:
        for t in c.transfers:
            if _ck(t.from_address) == victim_key:
                continue  # victim already added
            cp_label = t.counterparty.label
            if _ck(t.to_address) == current_holder_key:
                role = "Current holder of stolen position"
                row_class = "perp-row"
            elif cp_label and cp_label.category.value == "perpetrator":
                role = f"Perpetrator wallet ({cp_label.name})"
                row_class = "perp-row"
            elif cp_label:
                role = cp_label.name
                row_class = ""
            else:
                role = "Unlabeled (under investigation)"
                row_class = ""
            type_str = "Contract" if t.counterparty.is_contract else "EOA"
            notes_parts = []
            if cp_label:
                notes_parts.append(f"Category: {cp_label.category.value}")
                if cp_label.notes:
                    notes_parts.append(cp_label.notes)
            notes = " · ".join(notes_parts) or "—"
            _add(t.to_address, role, type_str, notes, row_class, chain=t.chain)

    # Sort: victim, perpetrators, then everyone else
    def _sort_key(w: dict[str, Any]) -> tuple[int, str]:
        if "victim" in w["row_class"]: return (0, w["address"])
        if "perp" in w["row_class"]: return (1, w["address"])
        return (2, w["address"])

    return sorted(seen.values(), key=_sort_key)


def _fmt_decimal(d: Decimal | None) -> str:
    if d is None:
        return "—"
    if d == d.to_integral_value():
        return f"{int(d):,}"
    return f"{d:,.6f}".rstrip("0").rstrip(".")


# v0.20.0 (round-13 arch follow-up): delegate to canonical helper.
# Templates that consume these strings already render a literal
# "USD " prefix around the value, so the bare-format variant is
# correct here. Fallback "(unknown)" preserves the prior contract.
from recupero._pricing import fmt_usd_bare_or as _fmt_usd_bare_or

def _fmt_usd(d: Decimal | None) -> str:
    return _fmt_usd_bare_or(d, fallback="(unknown)")


# v0.18.6 (round-11 PDF-HIGH-010): per-chain display-name map.
# Mirrors emit_brief._extract_primary_chain so both renderers agree.
_PRIMARY_CHAIN_DISPLAY: dict[str, str] = {
    "ethereum": "Ethereum",
    "arbitrum": "Arbitrum",
    "base": "Base",
    "bsc": "BNB Chain",
    "polygon": "Polygon",
    "solana": "Solana",
    "tron": "Tron",
    "bitcoin": "Bitcoin",
    "hyperliquid": "Hyperliquid",
}


def _resolve_primary_chain_display(primary_case) -> str:
    """Map a Case's chain enum to its human-facing display name."""
    raw = primary_case.chain.value if hasattr(primary_case.chain, "value") else str(primary_case.chain)
    return _PRIMARY_CHAIN_DISPLAY.get(raw, raw.capitalize() if raw else "Ethereum")


def _ensure_usd_prefix(s: str | None) -> str:
    """Normalize a maybe-USD string so the LE handoff never prints
    a bare number that reads as a token amount.

    v0.18.0 (round-11 forensic CRIT): operators / hand-edited
    freeze_brief.json files may carry total_usd as a bare
    "1037451.35" — emit_brief.usd() always adds `$`, but
    upstream-of-emit_brief paths and skip-editorial synthesizers
    don't always go through that helper. Templates that already
    prefix the prose with "USD " stay correct (extra `$` is then
    "USD $X" — verbose but unambiguous); templates without the
    `USD ` prose prefix (le.html.j2:274/283/293) now get a
    proper `$X` rendering.
    """
    if s is None or s == "":
        return "$0"
    s = str(s).strip()
    if s.startswith("$") or s.startswith("USD"):
        return s
    # Bare numeric? Add the $ prefix. Anything else (already-
    # formatted strings like "—") passes through unchanged.
    try:
        # Strip any commas before testing.
        Decimal(s.replace(",", ""))
        return f"${s}"
    except Exception:  # noqa: BLE001
        return s


def _build_issuer_freezable_ctx(
    raw: dict | None, chain: Chain | str,
) -> dict | None:
    """Convert a freeze_brief.json FREEZABLE entry into the template-
    friendly shape the issuer_freeze_request template expects.

    Returns None if ``raw`` is None — the template falls back to the
    single-asset/single-holder rendering path in that case (legacy
    callers or wallet-trace runs that skip freeze letters entirely).

    Output shape:

      {
        "token":                "USDC",
        "freeze_capability":    "HIGH",
        "total_usd_freezable":  "$7,097.58",
        "total_usd_suspected":  "$1,037,451.35",
        "holdings": [
          {"address": "...",
           "address_short": "0xABC…1234",
           "explorer_url": "https://etherscan.io/...",
           "amount": "1066.27 USDC",
           "usd": "$1,066.27",
           "status": "FREEZABLE"},
          ...
        ],
        "freezable_holdings":   [...only status=FREEZABLE...],
        "investigate_holdings": [...only status=INVESTIGATE...],
        "has_freezable":        True,
        "has_investigate":      True,
        "freezable_count":      2,
        "investigate_count":    4,
        "total_count":          6,
      }

    The template uses these to drive Sections 4 + 5 of the letter,
    which under the old behavior listed a single "current_holder"
    holding the original theft asset (e.g., 130 ETH at the first
    hop). With per-issuer holdings threaded through, each issuer
    gets a letter asking for a hold on the SPECIFIC stablecoin
    addresses that issuer actually controls.
    """
    if not raw:
        return None
    holdings_in = raw.get("holdings") or []
    holdings_out: list[dict] = []
    n_historical = 0
    n_current = 0
    for h in holdings_in:
        addr = h.get("address", "")
        # Propagate evidence_type + observed_at per-row so the issuer
        # freeze letter template's Evidence column renders the right
        # "current"/"historical" pill per holding.
        ev_type = h.get("evidence_type", "current_balance")
        if ev_type == "historical_inflow":
            n_historical += 1
        else:
            n_current += 1
        # v0.17.4 (round-10 audit CRIT): per-holding chain. Pre-v0.17.4
        # the URL was always built against `chain` (the case's source
        # chain), so freezable holdings discovered via cross-chain BFS
        # continuation (e.g., USDC on Polygon found from an Ethereum
        # seed) rendered as etherscan.io links. Compliance reviewers
        # clicked through to "address not found" — or worse, to a
        # third party's wallet that happened to share the same hex
        # address on Ethereum.
        per_holding_chain = h.get("chain") or chain
        holdings_out.append({
            "address": addr,
            "address_short": _short_addr(addr),
            "explorer_url": _address_explorer_url(addr, per_holding_chain),
            "amount": h.get("amount", "—"),
            "usd": h.get("usd", "—"),
            "status": h.get("status", "INVESTIGATE"),
            "evidence_type": ev_type,
            "observed_at": h.get("observed_at"),
        })

    freezable = [h for h in holdings_out if h["status"] == "FREEZABLE"]
    investigate = [h for h in holdings_out if h["status"] == "INVESTIGATE"]

    # Aggregate evidence_mode. Prefer the explicit value set by
    # emit_brief._extract_freezable; otherwise derive from per-row
    # counts so skip_editorial callers that didn't populate the
    # aggregate still get a sane value.
    explicit_mode = raw.get("evidence_mode")
    if explicit_mode in ("current_balance_only", "historical_only", "mixed"):
        evidence_mode = explicit_mode
    elif n_historical > 0 and n_current > 0:
        evidence_mode = "mixed"
    elif n_historical > 0:
        evidence_mode = "historical_only"
    else:
        evidence_mode = "current_balance_only"

    # v0.18.0 (round-11 forensic CRIT): hand-edited freeze_brief.json
    # entries may carry total_usd as a bare "1037451.35" with no `$`
    # prefix (emit_brief.usd() adds it, but pre-existing rows / R&D
    # paths may not). Normalize here so the LE handoff cover never
    # prints "1,037,451.35 of stolen funds is held" — which reads as
    # a token amount, not a dollar amount, to the LE reader.
    return {
        "token": raw.get("token") or "—",
        "freeze_capability": raw.get("freeze_capability") or "UNKNOWN",
        "total_usd_freezable": _ensure_usd_prefix(raw.get("total_usd")),
        "total_usd_suspected": _ensure_usd_prefix(raw.get("total_suspected_usd")),
        "holdings": holdings_out,
        "freezable_holdings": freezable,
        "investigate_holdings": investigate,
        "has_freezable": bool(freezable),
        "has_investigate": bool(investigate),
        "freezable_count": len(freezable),
        "investigate_count": len(investigate),
        "total_count": len(holdings_out),
        # Drive the issuer-letter template's evidence_mode branches.
        "evidence_mode": evidence_mode,
        "historical_count": n_historical,
        "current_balance_count": n_current,
        "earliest_observed": raw.get("earliest_observed"),
    }


def _build_le_routing_ctx(
    victim: VictimInfo,
    estimated_loss_usd: Decimal | None,
) -> dict[str, Any]:
    """Translate the structured LERoutingPlan into a template-friendly
    dict. The LE template iterates ``primary_routes``, ``state_routes``,
    and ``escalation_routes`` to generate the "Suggested Filing Routes"
    section.

    Loss-tier escalation thresholds are evaluated against
    ``estimated_loss_usd`` — which is the originally-stolen-asset's
    USD value at theft, as a reasonable approximation for routing
    decisions. This is NOT the freezable-USD total (which depends on
    the freeze_brief), because the routing decision needs to reflect
    the SCALE of the crime, not just the partial-recovery amount.
    """
    from recupero.worker._le_routing import recommend_le_routes

    plan = recommend_le_routes(
        state=victim.state,
        country=victim.country or victim.citizenship,
        total_loss_usd=estimated_loss_usd,
    )

    def _route_dict(route) -> dict[str, Any]:
        return {
            "name": route.name,
            "jurisdiction": route.jurisdiction,
            "url": route.url,
            "phone": route.phone,
            "email": route.email,
            "description": route.description,
            "expected_response": route.expected_response,
        }

    return {
        "has_routes": bool(
            plan.primary_routes or plan.state_routes or plan.escalation_routes
        ),
        "primary_routes":     [_route_dict(r) for r in plan.primary_routes],
        "state_routes":       [_route_dict(r) for r in plan.state_routes],
        "escalation_routes":  [_route_dict(r) for r in plan.escalation_routes],
        "notes":              list(plan.notes),
    }
